import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { Container, Card, Row, Text, Grid } from "@nextui-org/react";
import {Header} from "../components/Header.js";
import fs from 'fs/promises'
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export default function Home({latestComics}) {
  return (
    <>
      <Head>
        <title>XDCD - APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Text 
          h2
          size={60}
          css={{
            display:"flex",
            justifyContent:"center",
            mt: "30px",
            textGradient: "45deg, $yellow600 -20%, $red600 100%",
          }}
          weight="bold"
        >
          Latest Comics 
        </Text>
        <Grid.Container justify="center" >
        {
          latestComics.map(comic => {
            return (
              <Grid xs={6}>
                  <Link href={`/comic/${comic.id}`} key={comic.id}>
                    <img src={comic.img} alt={comic.alt} />
                </Link>
              </Grid>
            )
          })
        }
        </Grid.Container>
      </main>
      
    </>
  );
}

export async function getStaticProps(context){
  const files = await fs.readdir('./comics/')
  const lastNineComics = files.slice(-9, files.length)

  const promiseReadFiles = lastNineComics.map(async (file) => {
    const content = await fs.readFile(`./comics/${file}`, 'utf8')
    return JSON.parse(content)
  })

  const latestComics = await Promise.all(promiseReadFiles)
  

  return {
    props: {
      latestComics
    }

  }
}